# Data Preprocessing

## About this dataset

This dataset contains 7,668 movies with 15 features capturing a mix of content, performance, and production-related attributes. It provides a structured view of films across multiple decades, making it well-suited for both exploratory analysis and machine learning applications.

Each record includes key information such as:

Content attributes: genre, director, writer, and lead actor
Performance metrics: user rating (score) and number of votes
Financial data: production budget and box office gross
Contextual details: release date, country, runtime, and production company

The dataset combines categorical, numerical, and text-based fields, enabling a wide range of use cases including:

content-based recommendation systems
predictive modeling and ranking
feature engineering and data preprocessing workflows

While the dataset does not include user interaction data (e.g., clicks or watch history), it provides rich item-level features that are ideal for building content-driven recommendation systems and machine learning ranking models.

## Data loading + exploring

In [2]:
import pandas as pd
import numpy as np
from numpy.linalg import norm
import os

data = pd.read_csv("../data/raw/movies.csv")
data

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [3]:
df = data.copy()

### Understanding columns

In [4]:
df.groupby("country").size().sort_values(ascending=False)

country
United States                     5475
United Kingdom                     816
France                             279
Canada                             190
Germany                            117
Australia                           92
Japan                               81
India                               62
Italy                               61
Spain                               47
Hong Kong                           45
Ireland                             43
China                               40
South Korea                         35
Denmark                             32
New Zealand                         25
Sweden                              25
Mexico                              22
Norway                              12
West Germany                        12
Netherlands                         12
Iran                                10
Switzerland                         10
South Africa                         8
Czech Republic                       8
Russia                               8
Belgium                              8
Argentina                            8
Taiwan                               7
Hungary                              6
Thailand                             6
Brazil                               6
Yugoslavia                           5
Austria                              5
Israel                               5
Poland                               4
Philippines                          3
Turkey                               3
Finland                              3
Soviet Union                         2
Greece                               2
Vietnam                              2
Portugal                             2
Chile                                2
United Arab Emirates                 2
Federal Republic of Yugoslavia       2
Indonesia                            2
Iceland                              2
Colombia                             1
Malta                                1
Libya                                1
Jamaica                              1
Serbia                               1
Kenya                                1
Romania                              1
Republic of Macedonia                1
Panama                               1
Aruba                                1
Lebanon                              1
dtype: int64

In [5]:
df.groupby("year").size()

year
1980     92
1981    113
1982    126
1983    144
1984    168
1985    200
1986    200
1987    200
1988    200
1989    200
1990    200
1991    200
1992    200
1993    200
1994    200
1995    200
1996    200
1997    200
1998    200
1999    200
2000    200
2001    200
2002    200
2003    200
2004    200
2005    200
2006    200
2007    200
2008    200
2009    200
2010    200
2011    200
2012    200
2013    200
2014    200
2015    200
2016    200
2017    200
2018    200
2019    200
2020     25
dtype: int64

In [6]:
df.groupby("director").size().sort_values(ascending=False)

director
Woody Allen             38
Clint Eastwood          31
Directors               28
Steven Spielberg        27
Ron Howard              24
                        ..
Jeff Baena               1
Jefery Levy              1
Jeb Stuart               1
Jean-François Richet     1
Éva Gárdos               1
Length: 2949, dtype: int64

In [7]:
df.groupby("genre").size().sort_values(ascending=False)

genre
Comedy       2245
Action       1705
Drama        1518
Crime         551
Biography     443
Adventure     427
Animation     338
Horror        322
Fantasy        44
Mystery        20
Thriller       16
Family         11
Romance        10
Sci-Fi         10
Western         3
Musical         2
Sport           1
Music           1
History         1
dtype: int64

## Data Cleaning

In [8]:
df = df.dropna(axis=0)

In [9]:
# gets rid of all rows with votes kess than 5000
df = df.loc[df["votes"] > 5000, ["name", "genre", "year", "score", "votes", "director",	"writer", "star", "country",	"gross",	"runtime"]]

In [10]:
# creates new column which combines score and votes

df["popularityScore"] = df["score"] * df["votes"]

In [11]:
# deletes unwanted columns from dataset

del df["score"]
del df["votes"]

In [12]:
# buckets
# makes director, write and star have a value from 0-5 on how popular they are grouped with their name

df["director"] = df["director"].apply(lambda x: (x, (df[df["director"] == x]["director"].count()) // 10))
df["writer"] = df["writer"].apply(lambda x: (x, (df[df["writer"] == x]["writer"].count()) // 10))
df["star"] = df["star"].apply(lambda x: (x, (df[df["star"] == x]["star"].count()) // 10))

In [13]:
# removes all countrys with less than 8 occurences

df = df[df.groupby('country')['country'].transform('count') > 8]

In [14]:
# create buckets for countries around the world

def map_country(country):
    if country in ["United States", "Canada"]:
        return "USCan"
    elif country in ["United Kingdom", "Ireland"]:
        return "GB"
    elif country in ["Australia", "New Zealand"]:
        return "Oceania"
    elif country in ["France", "Germany", "Spain", "Italy", "Denmark", "Sweden", "Norway", "Netherlands"]:
        return "EU"
    elif country in ["Japan", "Hong Kong", "China", "South Korea"]:
        return "East Asia"
    else:
        return "Other"

df["country"] = df["country"].apply(map_country)

In [15]:
df.groupby("country").size()

country
EU            224
East Asia      85
GB            467
Oceania        59
Other          10
USCan        4092
dtype: int64

In [16]:
df

,name,genre,year,director,writer,star,country,gross,runtime,popularityScore
0,The Shining,Drama,1980,"(Stanley Kubrick, 0)","(Stephen King, 2)","(Jack Nicholson, 1)",GB,46998772.0,146.0,7786800.0
1,The Blue Lagoon,Adventure,1980,"(Randal Kleiser, 0)","(Henry De Vere Stacpoole, 0)","(Brooke Shields, 0)",USCan,58853106.0,104.0,377000.0
2,Star Wars: Episode V - The Empire Strikes Back,Action,1980,"(Irvin Kershner, 0)","(Leigh Brackett, 0)","(Mark Hamill, 0)",USCan,538375067.0,124.0,10440000.0
3,Airplane!,Comedy,1980,"(Jim Abrahams, 0)","(Jim Abrahams, 0)","(Robert Hays, 0)",USCan,83453539.0,88.0,1701700.0
4,Caddyshack,Comedy,1980,"(Harold Ramis, 0)","(Brian Doyle-Murray, 0)","(Chevy Chase, 1)",USCan,39846344.0,98.0,788400.0
...,...,...,...,...,...,...,...,...,...,...
7646,The Invisible Man,Drama,2020,"(Leigh Whannell, 0)","(Leigh Whannell, 1)","(Elisabeth Moss, 0)",USCan,143151000.0,124.0,1320600.0
7648,Bad Boys for Life,Action,2020,"(Adil El Arbi, 0)","(Peter Craig, 0)","(Will Smith, 2)",USCan,426505244.0,124.0,924000.0
7649,Sonic the Hedgehog,Action,2020,"(Jeff Fowler, 0)","(Pat Casey, 0)","(Ben Schwartz, 0)",USCan,319715683.0,99.0,663000.0
7650,Dolittle,Adventure,2020,"(Stephen Gaghan, 0)","(Stephen Gaghan, 0)","(Robert Downey Jr., 1)",USCan,245487753.0,101.0,296800.0
7651,The Call of the Wild,Adventure,2020,"(Chris Sanders, 0)","(Michael Green, 0)","(Harrison Ford, 2)",USCan,111105497.0,100.0,285600.0

### Save names for later

In [17]:
movie_names = []
for mov, year in zip(list(df["name"]), list(df["year"])):
    movie_names.append(f"{mov}({year})")

movie_names

['The Shining(1980)',
 'The Blue Lagoon(1980)',
 'Star Wars: Episode V - The Empire Strikes Back(1980)',
 'Airplane!(1980)',
 'Caddyshack(1980)',
 'Friday the 13th(1980)',
 'The Blues Brothers(1980)',
 'Raging Bull(1980)',
 'Superman II(1980)',
 'The Long Riders(1980)',
 'Any Which Way You Can(1980)',
 'Popeye(1980)',
 'Ordinary People(1980)',
 'Dressed to Kill(1980)',
 'Somewhere in Time(1980)',
 '9 to 5(1980)',
 'The Fog(1980)',
 "Heaven's Gate(1980)",
 'The Final Countdown(1980)',
 'Xanadu(1980)',
 'Brubaker(1980)',
 'American Gigolo(1980)',
 'Private Benjamin(1980)',
 'Motel Hell(1980)',
 'The Stunt Man(1980)',
 'Stardust Memories(1980)',
 'Bronco Billy(1980)',
 'The Octagon(1980)',
 'Indiana Jones and the Raiders of the Lost Ark(1981)',
 'An American Werewolf in London(1981)',
 'Escape from New York(1981)',
 'The Evil Dead(1981)',
 "Porky's(1981)",
 'Blow Out(1981)',
 'Clash of the Titans(1981)',
 'Excalibur(1981)',
 'Mad Max 2(1981)',
 'Stripes(1981)',
 'The Cannonball Run(1981)',
 'Thief(1981)',
 'Time Bandits(1981)',
 'Friday the 13th Part 2(1981)',
 'For Your Eyes Only(1981)',
 'Halloween II(1981)',
 'Taps(1981)',
 'Reds(1981)',
 'The Fox and the Hound(1981)',
 'Chariots of Fire(1981)',
 'Absence of Malice(1981)',
 'Tarzan the Ape Man(1981)',
 'Victory(1981)',
 'Arthur(1981)',
 'History of the World: Part I(1981)',
 'The Howling(1981)',
 'Dragonslayer(1981)',
 "Cutter's Way(1981)",
 'Quest for Fire(1981)',
 'The Final Conflict(1981)',
 'Mommie Dearest(1981)',
 'Deadly Blessing(1981)',
 'Outland(1981)',
 'S.O.B.(1981)',
 'The Beyond(1981)',
 'One from the Heart(1981)',
 'True Confessions(1981)',
 'Nighthawks(1981)',
 'Neighbors(1981)',
 'Wolfen(1981)',
 'Prince of the City(1981)',
 'Pennies from Heaven(1981)',
 'Fast Times at Ridgemont High(1982)',
 'Blade Runner(1982)',
 'The Thing(1982)',
 'Conan the Barbarian(1982)',
 'E.T. the Extra-Terrestrial(1982)',
 'First Blood(1982)',
 'An Officer and a Gentleman(1982)',
 'Grease 2(1982)',
 'Annie(1982)',
 'Poltergeist(1982)',
 '48 Hrs.(1982)',
 'Star Trek II: The Wrath of Khan(1982)',
 "Sophie's Choice(1982)",
 'Gandhi(1982)',
 'Tootsie(1982)',
 'Tron(1982)',
 'The Secret of NIMH(1982)',
 'The King of Comedy(1982)',
 'Rocky III(1982)',
 'The Beastmaster(1982)',
 'Creepshow(1982)',
 'The Man from Snowy River(1982)',
 'Pink Floyd: The Wall(1982)',
 'Cat People(1982)',
 'Friday the 13th Part III(1982)',
 'Firefox(1982)',
 'Halloween III: Season of the Witch(1982)',
 'The Dark Crystal(1982)',
 'The Verdict(1982)',
 'Pieces(1982)',
 'The World According to Garp(1982)',
 'Diner(1982)',
 'The Best Little Whorehouse in Texas(1982)',
 'The Year of Living Dangerously(1982)',
 'The Last Unicorn(1982)',
 'The Entity(1982)',
 'Airplane II: the Sequel(1982)',
 'The Toy(1982)',
 'The House on Sorority Row(1982)',
 'Evil Under the Sun(1982)',
 'Death Wish II(1982)',
 'Silent Rage(1982)',
 "Dead Men Don't Wear Plaid(1982)",
 'Amityville II: The Possession(1982)',
 'Missing(1982)',
 'Honkytonk Man(1982)',
 'Trail of the Pink Panther(1982)',
 'The Border(1982)',
 'Scarface(1983)',
 'The Outsiders(1983)',
 'Star Wars: Episode VI - Return of the Jedi(1983)',
 'Risky Business(1983)',
 "National Lampoon's Vacation(1983)",
 'Trading Places(1983)',
 'Superman III(1983)',
 'The Big Chill(1983)',
 'Staying Alive(1983)',
 'Jaws 3-D(1983)',
 'Christine(1983)',
 'Flashdance(1983)',
 'WarGames(1983)',
 'The Right Stuff(1983)',
 'Krull(1983)',
 'The Dead Zone(1983)',
 'Octopussy(1983)',
 'Private School(1983)',
 'Valley Girl(1983)',
 'Rumble Fish(1983)',
 'Videodrome(1983)',
 'Terms of Endearment(1983)',
 'Twilight Zone: The Movie(1983)',
 'Never Say Never Again(1983)',
 'A Christmas Story(1983)',
 'Cujo(1983)',
 'Sudden Impact(1983)',
 'Blue Thunder(1983)',
 'Breathless(1983)',
 'Psycho II(1983)',
 'Silkwood(1983)',
 'All the Right Moves(1983)',
 'The Keep(1983)',
 'Yentl(1983)',
 'Fire and Ice(1983)',
 'Yellowbeard(1983)',
 'The Meaning of Life(1983)',
 "Porky's II: The Next Day(1983)",
 'Something Wicked This Way Comes(1983)',
 'Star 80(1983)',
 'Gorky Park(1983)',
 'Lone Wolf McQuade(1983)',
 'Brainstorm(1983)',
 '10 to Midnight(1983)',
 'Uncommon Valor(1983)',
 'Spacehunter: Adventures in the Forbidden Zone(1983)',
 'High Road to China(1983)',
 'Under Fire(1983)',
 'Amityville 3-D(1983)',
 'The Osterman Weekend(1983)',
 'To Be or Not to Be(1983)',
 'Curse of the Pink Panther(1983)',
 'The Terminator(1984)',
 'Dune(1984)',
 'Ghostbusters(1984)',
 'The Karate Kid(1984)',
 'Once Upon a Time in America(1984)',
 'Police Academy(1984)',
 'Indiana Jones and the Temple of Doom(1984)',
 'Body Double(1984)',
 'A Nightmare on Elm Street(1984)',
 'Amadeus(1984)',
 'Beverly Hills Cop(1984)',
 'Red Dawn(1984)',
 'Footloose(1984)',
 'Revenge of the Nerds(1984)',
 'Gremlins(1984)',
 'Romancing the Stone(1984)',
 'Streets of Fire(1984)',
 'Sixteen Candles(1984)',
 'This Is Spinal Tap(1984)',
 'Top Secret!(1984)',
 'Conan the Destroyer(1984)',
 'Children of the Corn(1984)',
 'The Last Starfighter(1984)',
 'Splash(1984)',
 'Blood Simple(1984)',
 'The Natural(1984)',
 'Bachelor Party(1984)',
 'Friday the 13th: the Final Chapter(1984)',
 'Against All Odds(1984)',
 'Supergirl(1984)',
 'The Bounty(1984)',
 'Firestarter(1984)',
 'C.H.U.D.(1984)',
 'The Woman in Red(1984)',
 'Star Trek III: The Search for Spock(1984)',
 'Repo Man(1984)',
 '2010: the Year We Make Contact(1984)',
 'The Killing Fields(1984)',
 'The Cotton Club(1984)',
 'Starman(1984)',
 'Night of the Comet(1984)',
 'The Philadelphia Experiment(1984)',
 'Bolero(1984)',
 'Cannonball Run II(1984)',
 'Stranger Than Paradise(1984)',
 'The Ice Pirates(1984)',
 'A Passage to India(1984)',
 'Purple Rain(1984)',
 'The Hotel New Hampshire(1984)',
 'Missing in Action(1984)',
 'Greystoke: The Legend of Tarzan, Lord of the Apes(1984)',
 'Falling in Love(1984)',
 'Birdy(1984)',
 'The Company of Wolves(1984)',
 'Silent Night, Deadly Night(1984)',
 'The Pope of Greenwich Village(1984)',
 'Rhinestone(1984)',
 "The Razor's Edge(1984)",
 'Moscow on the Hudson(1984)',
 'The River(1984)',
 "A Soldier's Story(1984)",
 'City Heat(1984)',
 'The Brother from Another Planet(1984)',
 'Broadway Danny Rose(1984)',
 'Best Defense(1984)',
 'Weird Science(1985)',
 'The Goonies(1985)',
 'Back to the Future(1985)',
 'To Live and Die in L.A.(1985)',
 'Clue(1985)',
 'The Breakfast Club(1985)',
 'Cocoon(1985)',
 'Rambo: First Blood Part II(1985)',
 'Mask(1985)',
 'Legend(1985)',
 'The Return of the Living Dead(1985)',
 "St. Elmo's Fire(1985)",
 'Brazil(1985)',
 'Pale Rider(1985)',
 'Real Genius(1985)',
 'Commando(1985)',
 'Witness(1985)',
 'The Color Purple(1985)',
 'Silverado(1985)',
 'Rocky IV(1985)',
 'Ran(1985)',
 'Ladyhawke(1985)',
 'A Room with a View(1985)',
 'Red Sonja(1985)',
 'Fright Night(1985)',
 'Explorers(1985)',
 'Mad Max Beyond Thunderdome(1985)',
 'After Hours(1985)',
 'A View to a Kill(1985)',
 'Fletch(1985)',
 "A Nightmare on Elm Street 2: Freddy's Revenge(1985)",
 'Lifeforce(1985)',
 "Pee-wee's Big Adventure(1985)",
 'Out of Africa(1985)',
 'Day of the Dead(1985)',
 "National Lampoon's European Vacation(1985)",
 'Spies Like Us(1985)',
 'House(1985)',
 'Police Academy 2: Their First Assignment(1985)',
 'The Black Cauldron(1985)',
 'Friday the 13th: A New Beginning(1985)',
 'Runaway Train(1985)',
 'Re-Animator(1985)',
 "Brewster's Millions(1985)",
 'The Last Dragon(1985)',
 'Desperately Seeking Susan(1985)',
 'Jagged Edge(1985)',
 'Enemy Mine(1985)',
 'The Jewel of the Nile(1985)',
 'Once Bitten(1985)',
 'Into the Night(1985)',
 'The Sure Thing(1985)',
 'White Nights(1985)',
 'Silver Bullet(1985)',
 'Young Sherlock Holmes(1985)',
 "Porky's Revenge(1985)",
 'Year of the Dragon(1985)',
 'The Quiet Earth(1985)',
 'Mishima: A Life in Four Chapters(1985)',
 'A Chorus Line(1985)',
 "Cat's Eye(1985)",
 "Murphy's Romance(1985)",
 'Fandango(1985)',
 'Death Wish 3(1985)',
 "King Solomon's Mines(1985)",
 'American Warrior(1985)',
 'The Falcon and the Snowman(1985)',
 'Desert Hearts(1985)',
 'The Purple Rose of Cairo(1985)',
 'The Man with One Red Shoe(1985)',
 'Invasion U.S.A.(1985)',
 'Revolution(1985)',
 'Code of Silence(1985)',
 'Crimewave(1985)',
 'Santa Claus: The Movie(1985)',
 'Agnes of God(1985)',
 'Godzilla 1985(1985)',
 'Missing in Action 2: The Beginning(1985)',
 'The Care Bears Movie(1985)',
 'Top Gun(1986)',
 'Aliens(1986)',
 'Stand by Me(1986)',
 "Ferris Bueller's Day Off(1986)",
 'Crocodile Dundee(1986)',
 'Labyrinth(1986)',
 'Highlander(1986)',
 'Big Trouble in Little China(1986)',
 'Pretty in Pink(1986)',
 'Platoon(1986)',
 'Blue Velvet(1986)',
 'Manhunter(1986)',
 'Howard the Duck(1986)',
 'The Fly(1986)',
 'Little Shop of Horrors(1986)',
 'The Mosquito Coast(1986)',
 "River's Edge(1986)",
 '9½ Weeks(1986)',
 'The Golden Child(1986)',
 'Star Trek IV: The Voyage Home(1986)',
 'Short Circuit(1986)',
 'The Delta Force(1986)',
 'The Wraith(1986)',
 'The Color of Money(1986)',
 'Hoosiers(1986)',
 'Heartbreak Ridge(1986)',
 'Flight of the Navigator(1986)',
 'Cobra(1986)',
 'Peggy Sue Got Married(1986)',
 'The Mission(1986)',
 'Three Amigos!(1986)',
 'Maximum Overdrive(1986)',
 'Lucas(1986)',
 'Friday the 13th Part VI: Jason Lives(1986)',
 'The Money Pit(1986)',
 'Back to School(1986)',
 'About Last Night(1986)',
 'Critters(1986)',
 'The Texas Chainsaw Massacre 2(1986)',
 'From Beyond(1986)',
 'Sid and Nancy(1986)',
 'Henry: Portrait of a Serial Killer(1986)',
 'Night of the Creeps(1986)',
 'The Hitcher(1986)',
 'SpaceCamp(1986)',
 'Raw Deal(1986)',
 'Hannah and Her Sisters(1986)',
 'The Great Mouse Detective(1986)',
 'Ruthless People(1986)',
 'The Transformers: the Movie(1986)',
 'Troll(1986)',
 'At Close Range(1986)',
 'Something Wild(1986)',
 'Heartburn(1986)',
 'The Clan of the Cave Bear(1986)',
 "She's Gotta Have It(1986)",
 'Down by Law(1986)',
 'Poltergeist II: the Other Side(1986)',
 'Allan Quatermain and the Lost City of Gold(1986)',
 'Children of a Lesser God(1986)',
 'Invaders from Mars(1986)',
 'Down and Out in Beverly Hills(1986)',
 "April Fool's Day(1986)",
 'The Big Easy(1986)',
 'Pirates(1986)',
 'No Mercy(1986)',
 'Lady Jane(1986)',
 'Club Paradise(1986)',
 'Armed and Dangerous(1986)',
 'F/X(1986)',
 'King Kong Lives(1986)',
 'Wise Guys(1986)',
 'The Manhattan Project(1986)',
 'Gung Ho(1986)',
 "Murphy's Law(1986)",
 'Vamp(1986)',
 'Haunted Honeymoon(1986)',
 'Tough Guys(1986)',
 'The Best of Times(1986)',
 'Firewalker(1986)',
 'Witchboard(1986)',
 'Legal Eagles(1986)',
 'The Morning After(1986)',
 'The Princess Bride(1987)',
 'Full Metal Jacket(1987)',
 'Predator(1987)',
 'RoboCop(1987)',
 'Dirty Dancing(1987)',
 'Adventures in Babysitting(1987)',
 'The Untouchables(1987)',
 'Spaceballs(1987)',
 'Raising Arizona(1987)',
 'Lethal Weapon(1987)',
 'Near Dark(1987)',
 'Mannequin(1987)',
 'Masters of the Universe(1987)',
 'Fatal Attraction(1987)',
 'Empire of the Sun(1987)',
 'No Way Out(1987)',
 'The Witches of Eastwick(1987)',
 'The Running Man(1987)',
 'Black Widow(1987)',
 'Angel Heart(1987)',
 'Moonstruck(1987)',
 'Jaws: the Revenge(1987)',
 'Wall Street(1987)',
 'Good Morning, Vietnam(1987)',
 'A Nightmare on Elm Street 3: Dream Warriors(1987)',
 'Planes, Trains & Automobiles(1987)',
 'Overboard(1987)',
 'Beverly Hills Cop II(1987)',
 'Superman IV: The Quest for Peace(1987)',
 'The Secret of My Success(1987)',
 'Evil Dead II(1987)',
 'Innerspace(1987)',
 'The Living Daylights(1987)',
 'Over the Top(1987)',
 'Three Men and a Baby(1987)',
 'La Bamba(1987)',
 'The Monster Squad(1987)',
 'Prince of Darkness(1987)',
 'Broadcast News(1987)',
 'Harry and the Hendersons(1987)',
 'Creepshow 2(1987)',
 '*batteries not included(1987)',
 'Roxanne(1987)',
 'Dragnet(1987)',
 'Throw Momma from the Train(1987)',
 'Teen Wolf Too(1987)',
 'Ernest Goes to Camp(1987)',
 'The Hidden(1987)',
 'The Bedroom Window(1987)',
 'Barfly(1987)',
 'Blind Date(1987)',
 'Ishtar(1987)',
 'The Garbage Pail Kids Movie(1987)',
 'Radio Days(1987)',
 'Project X(1987)',
 "Three O'Clock High(1987)",
 'The Believers(1987)',
 'Death Wish 4: The Crackdown(1987)',
 'Cry Freedom(1987)',
 'The Pick-up Artist(1987)',
 'Someone to Watch Over Me(1987)',
 'Ironweed(1987)',
 "Who's That Girl(1987)",
 'Extreme Prejudice(1987)',
 'Matewan(1987)',
 'Suspect(1987)',
 'The Fourth Protocol(1987)',
 'Like Father Like Son(1987)',
 'Tin Men(1987)',
 'The Principal(1987)',
 'American Ninja 2: The Confrontation(1987)',
 'Leonard Part 6(1987)',
 'Hollywood Shuffle(1987)',
 'Nuts(1987)',
 'September(1987)',
 'Die Hard(1988)',
 'Midnight Run(1988)',
 'Beetlejuice(1988)',
 'Big(1988)',
 'Rain Man(1988)',
 'Running on Empty(1988)',
 'They Live(1988)',
 'Willow(1988)',
 'Crocodile Dundee II(1988)',
 'Heathers(1988)',
 'Coming to America(1988)',
 'Who Framed Roger Rabbit(1988)',
 'Mystic Pizza(1988)',
 'Cinema Paradiso(1988)',
 'Mississippi Burning(1988)',
 "Child's Play(1988)",
 'Twins(1988)',
 'The Naked Gun: from the Files of Police Squad!(1988)',
 'The Great Outdoors(1988)',
 'Cocktail(1988)',
 'My Neighbor Totoro(1988)',
 'Young Guns(1988)',
 'A Fish Called Wanda(1988)',
 'Working Girl(1988)',
 'Bloodsport(1988)',
 'The Last Temptation of Christ(1988)',
 'Married to the Mob(1988)',
 'The Land Before Time(1988)',
 'Rambo III(1988)',
 'The Accused(1988)',
 'Dangerous Liaisons(1988)',
 'Earth Girls Are Easy(1988)',
 'Hairspray(1988)',
 'Dead Ringers(1988)',
 'Bull Durham(1988)',
 'The Blob(1988)',
 'Oliver & Company(1988)',
 'Beaches(1988)',
 'Red Heat(1988)',
 'A Nightmare on Elm Street 4: The Dream Master(1988)',
 'The Adventures of Baron Munchausen(1988)',
 'Halloween 4: The Return of Michael Myers(1988)',
 'Elvira: Mistress of the Dark(1988)',
 'Mac and Me(1988)',
 'Above the Law(1988)',
 'Scrooged(1988)',
 'The Dead Pool(1988)',
 "I'm Gonna Git You Sucka(1988)",
 'Pumpkinhead(1988)',
 'Friday the 13th Part VII: the New Blood(1988)',
 'License to Drive(1988)',
 'Hellbound: Hellraiser II(1988)',
 'Frantic(1988)',
 'Colors(1988)',
 'My Stepmother Is an Alien(1988)',
 'A Cry in the Dark(1988)',
 'The Lair of the White Worm(1988)',
 'High Spirits(1988)',
 "Vampire's Kiss(1988)",
 'Return of the Living Dead II(1988)',
 'Eight Men Out(1988)',
 'Maniac Cop(1988)',
 'Women on the Verge of a Nervous Breakdown(1988)',
 "She's Having a Baby(1988)",
 'Tequila Sunrise(1988)',
 'Night of the Demons(1988)',
 'Biloxi Blues(1988)',
 'Cocoon: the Return(1988)',
 'Poltergeist III(1988)',
 'Waxwork(1988)',
 'Funny Farm(1988)',
 'Fright Night Part 2(1988)',
 'Caddyshack II(1988)',
 'School Daze(1988)',
 'Johnny Be Good(1988)',
 'Short Circuit 2(1988)',
 'The Serpent and the Rainbow(1988)',
 'Monkey Shines(1988)',
 'Phantasm II(1988)',
 'Tucker: The Man and His Dream(1988)',
 'Action Jackson(1988)',
 'Bright Lights, Big City(1988)',
 'Shoot to Kill(1988)',
 'The Beast of War(1988)',
 'Lady in White(1988)',
 'Gorillas in the Mist(1988)',
 'Alien Nation(1988)',
 'Betrayed(1988)',
 'Miracle Mile(1988)',
 'Critters 2(1988)',
 'Dead Heat(1988)',
 'Talk Radio(1988)',
 'The Milagro Beanfield War(1988)',
 'Bird(1988)',
 'Punchline(1988)',
 'Little Nikita(1988)',
 'Red Scorpion(1988)',
 'Another Woman(1988)',
 'Ernest Saves Christmas(1988)',
 'Moon Over Parador(1988)',
 'Indiana Jones and the Last Crusade(1989)',
 'Road House(1989)',
 'Batman(1989)',
 "Bill & Ted's Excellent Adventure(1989)",
 'Dead Poets Society(1989)',
 'The Little Mermaid(1989)',
 'The Abyss(1989)',
 'Back to the Future Part II(1989)',
 'Do the Right Thing(1989)',
 'Honey, I Shrunk the Kids(1989)',
 'Turner & Hooch(1989)',
 'Sex, Lies, and Videotape(1989)',
 'When Harry Met Sally...(1989)',
 'Major League(1989)',
 'Steel Magnolias(1989)',
 'Pet Sematary(1989)',
 'Uncle Buck(1989)',
 'Ghostbusters II(1989)',
 'Tango & Cash(1989)',
 'Born on the Fourth of July(1989)',
 'Glory(1989)',
 'Parenthood(1989)',
 'Lethal Weapon 2(1989)',
 "National Lampoon's Christmas Vacation(1989)",
 "The 'Burbs(1989)",
 'License to Kill(1989)',
 'Harlem Nights(1989)',
 'Lock Up(1989)',
 'Warlock(1989)',
 'See No Evil, Hear No Evil(1989)',
 'Casualties of War(1989)',
 'The Package(1989)',
 'The War of the Roses(1989)',
 'The Wizard(1989)',
 'UHF(1989)',
 "Look Who's Talking(1989)",
 'Star Trek V: The Final Frontier(1989)',
 'All Dogs Go to Heaven(1989)',
 'Cyborg(1989)',
 'Always(1989)',
 'Leviathan(1989)',
 'Best of the Best(1989)',
 'Dead Calm(1989)',
 'Kickboxer(1989)',
 'Black Rain(1989)',
 'Troop Beverly Hills(1989)',
 'Driving Miss Daisy(1989)',
 'Drugstore Cowboy(1989)',
 'A Nightmare on Elm Street 5: The Dream Child(1989)',
 'Halloween 5: The Revenge of Michael Myers(1989)',
 'DeepStar Six(1989)',
 'Sea of Love(1989)',
 'K-9(1989)',
 'Lean on Me(1989)',
 'Henry V(1989)',
 'Friday the 13th Part VIII: Jason Takes Manhattan(1989)',
 'Valmont(1989)',
 'The Fabulous Baker Boys(1989)',
 'Shocker(1989)',
 'Next of Kin(1989)',
 'Mystery Train(1989)',
 'Gleaming the Cube(1989)',
 'Fletch Lives(1989)',
 'Communion(1989)',
 'Crimes and Misdemeanors(1989)',
 'Let It Ride(1989)',
 'Chances Are(1989)',
 'The Dream Team(1989)',
 'Little Nemo: Adventures in Slumberland(1989)',
 'New York Stories(1989)',
 'Blind Fury(1989)',
 "We're No Angels(1989)",
 'Johnny Handsome(1989)',
 'Fat Man and Little Boy(1989)',
 'Police Academy 6: City Under Siege(1989)',
 'Pink Cadillac(1989)',
 'Three Fugitives(1989)',
 'Robot Jox(1989)',
 'No Holds Barred(1989)',
 'Parents(1989)',
 'Longtime Companion(1989)',
 'A Dry White Season(1989)',
 'The Toxic Avenger Part II(1989)',
 'Goodfellas(1990)',
 'The Godfather: Part III(1990)',
 'Total Recall(1990)',
 'Pretty Woman(1990)',
 'Home Alone(1990)',
 'Ghost(1990)',
 'Dances with Wolves(1990)',
 'Tremors(1990)',
 'Die Hard 2(1990)',
 'Misery(1990)',
 'Kindergarten Cop(1990)',
 'The Bonfire of the Vanities(1990)',
 'Teenage Mutant Ninja Turtles(1990)',
 'Edward Scissorhands(1990)',
 'The Hunt for Red October(1990)',
 'Dick Tracy(1990)',
 'Awakenings(1990)',
 'Wild at Heart(1990)',
 'Predator 2(1990)',
 'RoboCop 2(1990)',
 "Jacob's Ladder(1990)",
 'Back to the Future Part III(1990)',
 'Darkman(1990)',
 'The Hot Spot(1990)',
 'Cry-Baby(1990)',
 'Presumed Innocent(1990)',
 'Arachnophobia(1990)',
 'Days of Thunder(1990)',
 'King of New York(1990)',
 'Gremlins 2: The New Batch(1990)',
 'Rocky V(1990)',
 'Young Guns II(1990)',
 "Miller's Crossing(1990)",
 'Revenge(1990)',
 'Mermaids(1990)',
 "Child's Play 2(1990)",
 'Joe Versus the Volcano(1990)',
 'Slacker(1990)',
 'Flatliners(1990)',
 'Quigley Down Under(1990)',
 'Nightbreed(1990)',
 'The Two Jakes(1990)',
 'Lionheart(1990)',
 'Internal Affairs(1990)',
 'Problem Child(1990)',
 'The Rescuers Down Under(1990)',
 'House Party(1990)',
 'Another 48 Hrs.(1990)',
 'Night of the Living Dead(1990)',
 'Pacific Heights(1990)',
 'Postcards from the Edge(1990)',
 'Hard to Kill(1990)',
 'The NeverEnding Story II: The Next Chapter(1990)',
 'Leatherface: Texas Chainsaw Massacre III(1990)',
 'Frankenhooker(1990)',
 'State of Grace(1990)',
 'Bird on a Wire(1990)',
 'Memphis Belle(1990)',
 'The Adventures of Ford Fairlane(1990)',
 'Marked for Death(1990)',
 'Dreams(1990)',
 'Air America(1990)',
 'Class of 1999(1990)',
 'Death Warrant(1990)',
 'Quick Change(1990)',
 'Hardware(1990)',
 'Mr. Destiny(1990)',
 'The Freshman(1990)',
 'Navy Seals(1990)',
 'Graveyard Shift(1990)',
 'The Sheltering Sky(1990)',
 'Dark Angel(1990)',
 "Mo' Better Blues(1990)",
 'Bad Influence(1990)',
 'Tales from the Darkside: The Movie(1990)',
 'The Rookie(1990)',
 'Green Card(1990)',
 'Metropolitan(1990)',
 'Havana(1990)',
 'The Russia House(1990)',
 'White Hunter Black Heart(1990)',
 'Avalon(1990)',
 'Fire Birds(1990)',
 'Alice(1990)',
 'Desperate Hours(1990)',
 'Cadence(1990)',
 'Ernest Goes to Jail(1990)',
 'Two Evil Eyes(1990)',
 'Trust(1990)',
 'Stanley & Iris(1990)',
 'Terminator 2: Judgment Day(1991)',
 'Point Break(1991)',
 'The Silence of the Lambs(1991)',
 'Hook(1991)',
 'Boyz n the Hood(1991)',
 'Cape Fear(1991)',
 'The Addams Family(1991)',
 'Thelma & Louise(1991)',
 'Robin Hood: Prince of Thieves(1991)',
 'The Doors(1991)',
 'Beauty and the Beast(1991)',

In [18]:
del df["name"]
df

,genre,year,director,writer,star,country,gross,runtime,popularityScore
0,Drama,1980,"(Stanley Kubrick, 0)","(Stephen King, 2)","(Jack Nicholson, 1)",GB,46998772.0,146.0,7786800.0
1,Adventure,1980,"(Randal Kleiser, 0)","(Henry De Vere Stacpoole, 0)","(Brooke Shields, 0)",USCan,58853106.0,104.0,377000.0
2,Action,1980,"(Irvin Kershner, 0)","(Leigh Brackett, 0)","(Mark Hamill, 0)",USCan,538375067.0,124.0,10440000.0
3,Comedy,1980,"(Jim Abrahams, 0)","(Jim Abrahams, 0)","(Robert Hays, 0)",USCan,83453539.0,88.0,1701700.0
4,Comedy,1980,"(Harold Ramis, 0)","(Brian Doyle-Murray, 0)","(Chevy Chase, 1)",USCan,39846344.0,98.0,788400.0
...,...,...,...,...,...,...,...,...,...
7646,Drama,2020,"(Leigh Whannell, 0)","(Leigh Whannell, 1)","(Elisabeth Moss, 0)",USCan,143151000.0,124.0,1320600.0
7648,Action,2020,"(Adil El Arbi, 0)","(Peter Craig, 0)","(Will Smith, 2)",USCan,426505244.0,124.0,924000.0
7649,Action,2020,"(Jeff Fowler, 0)","(Pat Casey, 0)","(Ben Schwartz, 0)",USCan,319715683.0,99.0,663000.0
7650,Adventure,2020,"(Stephen Gaghan, 0)","(Stephen Gaghan, 0)","(Robert Downey Jr., 1)",USCan,245487753.0,101.0,296800.0
7651,Adventure,2020,"(Chris Sanders, 0)","(Michael Green, 0)","(Harrison Ford, 2)",USCan,111105497.0,100.0,285600.0

## Binary Encoding

In [19]:
countrys = ["USCan", "GB", "Oceania", "EU", "East Asia", "Other"]
df["country"] = df["country"].apply(lambda country: [1 if country == c else 0 for c in countrys])

In [20]:
genres = ["Comedy", "Action", "Drama", "Crime", "Biography", "Adventure", "Animation", "Horror", "Fantasy", "Mystery", "Thriller", "Family", "Romance", "Sci-Fi", "Music"]
df["genre"] = df["genre"].apply(lambda genre: [1 if genre == g else 0 for g in genres])

## Normalization

### Continuous

In [21]:
gross = list(df["gross"].sort_values(ascending=False))
df["gross"] = df["gross"].apply(lambda value: round(value/gross[0], 2))

In [22]:
popularityScore = list(df["popularityScore"].sort_values(ascending=False))
df["popularityScore"] = df["popularityScore"].apply(lambda value: round(value/popularityScore[0], 2))

In [23]:
runtime = list(df["runtime"].sort_values(ascending=False))
df["runtime"] = df["runtime"].apply(lambda value: round(value/runtime[0], 2))

In [24]:
year = list(df["year"].sort_values(ascending=False))
diff = year[0] - year[-1]
df["year"] = df["year"].apply(lambda value: round((year[0]-value)/diff, 2))

### Discrete

In [25]:
# remember now that these are in 4 buckets of popularity
# normalize using 4 buckets

df["writer"] = df["writer"].apply(lambda x: round(x[1]/4, 2))
df["star"] = df["star"].apply(lambda x: round(x[1]/4, 2))
df["director"] = df["director"].apply(lambda x: round(x[1]/4, 2))

In [26]:
df

,genre,year,director,writer,star,country,gross,runtime,popularityScore
0,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1.0,0.0,0.50,0.25,"[0, 1, 0, 0, 0, 0]",0.02,0.54,0.35
1,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1.0,0.0,0.00,0.00,"[1, 0, 0, 0, 0, 0]",0.02,0.38,0.02
2,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1.0,0.0,0.00,0.00,"[1, 0, 0, 0, 0, 0]",0.19,0.46,0.47
3,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1.0,0.0,0.00,0.00,"[1, 0, 0, 0, 0, 0]",0.03,0.32,0.08
4,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1.0,0.0,0.00,0.25,"[1, 0, 0, 0, 0, 0]",0.01,0.36,0.04
...,...,...,...,...,...,...,...,...,...
7646,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.0,0.0,0.25,0.00,"[1, 0, 0, 0, 0, 0]",0.05,0.46,0.06
7648,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.0,0.0,0.00,0.50,"[1, 0, 0, 0, 0, 0]",0.15,0.46,0.04
7649,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.0,0.0,0.00,0.00,"[1, 0, 0, 0, 0, 0]",0.11,0.37,0.03
7650,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.0,0.0,0.00,0.25,"[1, 0, 0, 0, 0, 0]",0.09,0.37,0.01
7651,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0.0,0.0,0.00,0.50,"[1, 0, 0, 0, 0, 0]",0.04,0.37,0.01

# Movie Recommender

## Create similarity matrix

In [27]:
def cosine_sim(a, b):
    # Calculate cosine similarity between two vectors
    return round(np.dot(a, b) / (norm(a) * norm(b)), 3)

def flatten_data(row):
    return np.array([item for idx in row for item in (idx if isinstance(idx, list) else [idx])])

#takes 12.5 minutes
# 11.5 minutes

if not os.path.isfile("../data/cosine_data/external/similarity.csv"):
    # Precompute the flattened data
    precomputed_data = [flatten_data(row) for row in df.values]

    # Initialize an empty matrix with the same shape as df
    matrix = []

    for row in range(len(df)):
        if row % 1000 == 0:
            print(row)
        # Calculate cosine similarity for each pair of rows and build row_list using a list comprehension
        row_list = [cosine_sim(precomputed_data[row], precomputed_data[col]) for col in range(len(df))]
        matrix.append(row_list)

    similarity_matrix_df = pd.DataFrame(matrix)
else:
    similarity_matrix_df = pd.read_csv("../data/cosine_data/external/similarity.csv", header=None)

# turn it into a np array
similarity_matrix=np.array(similarity_matrix_df)

## Run inference

In [28]:
movies_liked = np.random.choice(np.array(movie_names), 3)
print(movies_liked)

# movies_liked = []

['Barb Wire(1996)' 'The River Wild(1994)' 'The Santa Clause 2(2002)']

### Similar to individual liked movies

In [29]:
# List of movies enjoyed (chosen from this list: https://docs.google.com/spreadsheets/d/1aLpwOlVCnS4qS3lUn5OKklVW23UXmu1Vb5on0MNuAEw/edit?usp=sharing)

# Major movies from 1980-2020 should be included
print("Movies Liked:","\n")
print(movies_liked, "\n")
print("Recommendations:","\n")
###############

indices = []
for movie in movies_liked:
  indices.append(movie_names.index(movie))

best_recs = []
similarities = {} ## movieid : [similarity, movieid(original)]
for movie_i in indices:

  tmp = similarity_matrix[int(movie_i),:]
  highest_vals = sorted(tmp,reverse=True)[1:4]


  for val in highest_vals:
    new_best_recs = np.where(tmp==val)[0]
    best_recs.extend(new_best_recs)
    for rec in new_best_recs:
      rating = round(100*val,2)
      if rec in similarities and rating>similarities[rec][0]:
        similarities[rec]=[rating,movie_i]
      elif rec not in similarities:
        similarities[rec]=[rating,movie_i]

similarities_sorted = dict(sorted(similarities.items(), key=lambda x:x[1], reverse=True))


for rec in similarities_sorted:
  if movie_names[rec] not in movies_liked:
    print(movie_names[rec]+"............"+str(similarities[rec][0])+"% match to "+movie_names[similarities[rec][1]])

Movies Liked:

['Barb Wire(1996)' 'The River Wild(1994)' 'The Santa Clause 2(2002)']

Recommendations:

Chocolat(2000)............99.8% match to The Santa Clause 2(2002)
Father of the Bride Part II(1995)............99.8% match to Barb Wire(1996)
Life(1999)............99.8% match to Barb Wire(1996)
The Replacements(2000)............99.8% match to Barb Wire(1996)
Keeping the Faith(2000)............99.8% match to Barb Wire(1996)
Dr. T & the Women(2000)............99.8% match to Barb Wire(1996)
28 Days Later...(2002)............99.7% match to The Santa Clause 2(2002)
Possession(2002)............98.7% match to The Santa Clause 2(2002)
Code 46(2003)............98.7% match to The Santa Clause 2(2002)
Anonymous(2011)............98.7% match to The Santa Clause 2(2002)
Home Alone 2: Lost in New York(1992)............98.5% match to The River Wild(1994)
National Lampoon's European Vacation(1985)............98.3% match to The River Wild(1994)
Stand by Me(1986)............98.1% match to The River Wild(1994)

### Similar to all liked movies

In [30]:
def movie_recommendations(movies_liked, similarity_matrix, movie_names):
    indices = [movie_names.index(movie) for movie in movies_liked]

    best_recs = []
    similarities = {}
    similarity_row = np.mean([similarity_matrix[i] for i in indices], axis=0)

    highest_vals = sorted(similarity_row, reverse=True)[1:10]

    for val in highest_vals:
        new_best_recs = np.where(similarity_row==val)[0]
        best_recs.extend(new_best_recs)
        for rec in new_best_recs:
            similarities[rec] = max(similarities.get(rec, 0), 100*val)

    similarities_sorted = dict(sorted(similarities.items(), key=lambda x:x[1], reverse=True))

    rec_list = []
    for rec in similarities_sorted:
        if movie_names[rec] not in movies_liked:
            rec_list.append(f"{movie_names[rec]}...{round(similarities[rec], 2)}% match")

    return rec_list

# Print recommendations
print("Movies most similar to all the liked movies:","\n")
print(*movie_recommendations(movies_liked, similarity_matrix, movie_names), sep='\n')

Movies most similar to all the liked movies:

Ironweed(1987)...60.53% match
Disclosure(1994)...60.37% match
Havana(1990)...60.23% match
A Chorus Line(1985)...60.2% match
JFK(1991)...60.2% match
Platoon(1986)...60.17% match
9½ Weeks(1986)...60.17% match
An Officer and a Gentleman(1982)...60.13% match
Jungle Fever(1991)...60.13% match

## Save Dataframes to csv

In [31]:
if not os.path.isfile("../data/cosine_data/external/movie_names.csv"):
    movie_names_df = pd.DataFrame(movie_names)


    processed_dir = "../data/cosine_data/external"
    if os.path.exists(processed_dir):
        processed_path = processed_dir + "/movie_names.csv"
        movie_names_df.to_csv(processed_path, index=False)
        print("Saved movie names dataset: %s", processed_path)
    else:
        print("path does not exist")
else:
    print("file already exists")

file already exists

In [32]:
if not os.path.isfile("../data/cosine_data/external/similarity.csv"):

    processed_dir = "../data/cosine_data/external"
    if os.path.exists(processed_dir):
        processed_path = processed_dir + "/similarity.csv"
        similarity_matrix_df.to_csv(processed_path, index=False)
        print("Saved similarity dataset: %s", processed_path)
    else:
        print("path does not exist")
else:
    print("file already exists")

file already exists

In [33]:
if not os.path.isfile("../data/cosine_data/processed/movies_processed.csv"):

    processed_dir = "../data/cosine_data/processed"
    if os.path.exists(processed_dir):
        processed_path = processed_dir + "/movies_processed.csv"
        df.to_csv(processed_path, index=False)
        print("Saved processed movies dataset: %s", processed_path)
    else:
        print("path does not exist")
else:
    print("file already exists")

file already exists